# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_jarrett 129C4A67BB9B6E293E29D2F7E7A699A45DC0DD8A
  - &garage age1sunhw6ggvycqul4esu7a0knvwtaa94v0j3c7ldefv2c88d8m3pws0myl99
creation_rules:
  - path_regex: secrets/garage.yaml$
    pgp: *admin_jarrett
    age: *garage

  - path_regex: secrets/nixos-binary-cache.yaml$
    pgp: *admin_jarrett
